### ISSUE TITLE
Package Structure TODOs

### ISSUE THREAD

**Issue by christopherkenny** [MatthewBJane/ThemePark#26]
These are a few small things from #17 that can help make sure this follows some best practices (making future edits easier).

- [x] run `usethis::use_github_action_check_standard()` to initialize the GitHub Actions automatic checking
- [x] (OPTIONAL, but helpful)  run `usethis::use_pkgdown_github_pages()` to give a default pkgdown site
- [x] Add PR and issues templates to suggest using the new functions and giving some standards for what things people should change (such as adding their name to the README and package description as a 'ctb' (contributor)).
- [x] Adding tests (even if they're super simple and just checking some return types or error messages). This can be added with `usethis::use_testthat()`

**Comment by MatthewBJane** [comment]
So if we do these things, would we be ready to submit to CRAN? Do I have to make a local branch and then push to github when I run these tests

**Comment by christopherkenny** [comment]
Yeah, assuming they don't flag any issues, then it would be in pretty good shape to send to CRAN. Yeah, you can just run them from a local branch and push once they run. (It's quick.) It will add some documentation items and .Rbuildignore them.

**Comment by MatthewBJane** [comment]
Okay I just committed the changes. I did not do the PR or issues template, is that necessary?

**Comment by christopherkenny** [comment]
No, it's definitely not necessary. Thanks!

**Comment by MatthewBJane** [comment]
Okay would you mind adding some tests? I am a bit confused how it works. I added the folder for it and a file called test-ThemePark. Also @christopherkenny and @lukepilling you can check out the pkgdown site at matthewbjane.com/theme_park

**Comment by lukepilling** [comment]
The site looks great! Good choice of colour scheme 👍  absolutely no idea how tests for packages work, sorry

**Comment by christopherkenny** [comment]
Love the bootswatch choice. I'll add some tests tonight. I'll also add a bit of structure to the reference page. Happy to explain what I'm adding once the basics are in.

**Comment by christopherkenny** [comment]
Looks like the sysfonts dependency doesn't correctly import packages, so this is a bit trickier than expected. Will work on that

**Comment by christopherkenny** [comment]
Okay that issue is resolved. The package now passes checks. I can add some default tests for the themes over the next few days.

**Comment by MatthewBJane** [comment]
Awesome thanks a ton @christopherkenny

**Comment by christopherkenny** [comment]
Closed by https://github.com/MatthewBJane/ThemePark/commit/284d0c644cac4be9c811d3bbfd5b3af36c0d1721
