### ISSUE TITLE
Need to use as.character for scale_color_manual

### ISSUE THREAD

**Issue by jebyrnes** [MatthewBJane/ThemePark#35]
I've run into a funny problem where the color vectors don't work in combination with `scale_color_manual()` and its values argument, unless you again `as.character()` them. Below are three plots with palmerpenguins. The middle, however, has grey colors, when it should not. What's going on here? The class of the color vector is character, so.....

``` r
#libraries
library(ggplot2)
library(ThemePark)
library(palmerpenguins)

# Base of the plot
pen_plot_base <- ggplot(data = penguins,
                        mapping = aes(x = body_mass_g,
                                      y = species,
                                      color = species))

# Works
pen_plot_base +
  geom_jitter(position = position_jitter(height = 0.1),
              alpha = 0.7) +
  scale_color_manual(values = c("#a62675ff", "#fdf6faff", "#d74ea2ff"))
#> Warning: Removed 2 rows containing missing values (`geom_point()`).
```

![](https://i.imgur.com/gpiexXH.png)

``` r



# Gray
pen_plot_base +
  geom_jitter(position = position_jitter(height = 0.1),
              alpha = 0.7) +
  scale_color_manual(values = barbie_theme_colors[1:3])
#> Warning: Removed 2 rows containing missing values (`geom_point()`).
```

![](https://i.imgur.com/2SGFLjd.png)

``` r


# Works
pen_plot_base +
  geom_jitter(position = position_jitter(height = 0.1),
              alpha = 0.7) +
  scale_color_manual(values = as.character(barbie_theme_colors[1:3]))
#> Warning: Removed 2 rows containing missing values (`geom_point()`).
```

![](https://i.imgur.com/4IghOuJ.png)

<sup>Created on 2023-09-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by lukepilling** [comment]
Seems to be because we assign names to the values in `barbie_theme_colors` so they can be referenced like `barbie_theme_colors["text"]`

See what happens here:

![image](https://github.com/MatthewBJane/theme_park/assets/4245328/3285aae7-81a9-40ba-88b6-941edc8abf71)

How to get around this, I do not know!

**Comment by christopherkenny** [comment]
Yeah, this is a function of ggplot2's design, which allows you to use the names within scale_manual to indicate the colors for each. Easiest thing is to just use `unname()` around it first. Best practice is normally to create a vector that has the names from your data as the names of the colors in the vector.
