### ISSUE TITLE
repo name?

### ISSUE THREAD

**Issue by jebyrnes** [MatthewBJane/ThemePark#36]
This is really small, but, because the repo name and package name don't agree, 

`pacman::p_load_gh("MatthewBJane/theme_park)"` 

does not work.

(I loooove this package and want to spread it to my collaborators! `p_load()` and its ilk are such an easy way to do so....)

**Comment by MatthewBJane** [comment]
@christopherkenny @lukepilling Can I just change the repo name without anything serious happening? I know the links that are out there won't work, but its probably for the best?

**Comment by christopherkenny** [comment]
Yeah, you can just change it. The links redirect for a certain amount of time.

**Comment by MatthewBJane** [comment]
Repo name has been changed. Closing this issue.
